ChallengeModal.tsx: set komi to 5.5 if it is not defined
online-go/online-go.com pull request #1735
Opened 2022-03-06 22:41 UTC by maurelio1234

Fixes #1727 

In the end of the day the problem seems to be unrelated to https://github.com/online-go/online-go.com/pull/1721
It seems that there's a confusion on the `komi` property.
In `challenges.d.ts` it is defined as a `number` whereas we clearly send a string to the backend.

The constructor of `ChallengeModal` contains code to "fix dirty data", so I guess it's the right place to check if the `komi` is valid.
The only thing I don't understand (yet) is why the default komi is set to the empty string, as I had this value on my local environment already, even though I cannot see traces of it on the code.

## Proposed Changes

  - Replace `null` check by truthy check, so that the empty string is replaced by the valid default handicap

2022-03-07 00:17 UTC, benjaminpjones commented
> Replace `null` check by truthy check

I think 0.0 is a valid setting, and a truthy check would change it to 5.5, right?

2022-03-07 08:05 UTC, maurelio1234 commented
> I think 0.0 is a valid setting, and a truthy check would change it to 5.5, right?

that's what's weird about this code... 0.0 (the number) is not valid, "0" or "0.0" are.
i will do some tests, I'd prefer dealing with actual numbers then stringifyed numbers.
i will check if changing the type in `challenges.d.ts` works...

2022-03-07 08:10 UTC, BHydden commented
IIRC, numbers are (annoyingly) stringified to help the translator, as not all languages handle numbers the same (position within a sentence, etc.) and the translator code takes strings as input... but I could be wrong 😛

2022-03-07 16:45 UTC, benjaminpjones commented
@maurelio1234 Oh got it that makes sense, thanks. I really would have expected that to be a number!

2022-03-08 12:46 UTC, anoek requested changes
Can we add a check to see if it's not a number as well? Otherwise if/when we get around to fixing this component so `komi` is a number like it should be, this code will start replacing `0` with `5.5` as noted above.

2022-03-09 11:50 UTC, anoek commented
Thanks for the fix @maurelio1234 !

2022-03-09 11:50 UTC, merged