Move rules out of the black player card
online-go/online-go.com pull request #2563
Opened 2024-02-06 18:55 UTC by dexonsmith

In the black player card, the rules codes can be mistaken for initials of the black player.  Move them out, just below the player cards, into an area for condensed game information with small font.

- Rules, aligned right.
- Ranked games, "Ranked", aligned left.

This is an option for addressing [feedback from the forums](https://forums.online-go.com/t/the-ruleset-of-the-game-should-be-easier-to-see/39165).

Draft for discussion. I'll post screenshots in a moment.

2024-02-06 18:58 UTC, dexonsmith commented
Two examples:

An unranked handicap game:
<img width="383" alt="Image 2" src="https://github.com/online-go/online-go.com/assets/1334620/489f0099-4f15-4d10-9365-4799c0ddf9c9">

A ranked even game:
<img width="380" alt="Image" src="https://github.com/online-go/online-go.com/assets/1334620/d9cb4656-149c-4fb1-bbe8-432ddc6ee9d8">

2024-02-06 20:47 UTC, GreenAsJade approved these changes

2024-02-06 21:40 UTC, GreenAsJade requested changes
I realised a couple of things:

 - When there is a player to move, it's getting in between the cards and this.   This should always be right below the cards.
 
  - This should be turned off in Zen mode

2024-02-06 21:51 UTC, dexonsmith commented
> * When there is a player to move, it's getting in between the cards and this.   This should always be right below the cards.

It looks correct to me:
<img width="394" alt="Image 5" src="https://github.com/online-go/online-go.com/assets/1334620/5d67e0da-e667-4386-bb82-35996aeab5ff">
<img width="550" alt="Image 6" src="https://github.com/online-go/online-go.com/assets/1334620/40bf97e4-1e48-458b-b698-227c7e79a497">

Am I looking at the right thing?

2024-02-06 21:52 UTC, dexonsmith commented
Looking at the code, I just noticed there's a rengo header (somewhat confusingly) inside of `<PlayerCards/>`. I can move that text to this level.

2024-02-06 22:17 UTC, dexonsmith commented
> > * When there is a player to move, it's getting in between the cards and this.   This should always be right below the cards.
> 
> It looks correct to me: 
> [...]
> Looking at the code, I just noticed there's a rengo header (somewhat confusingly) inside of `<PlayerCards/>`. I can move that text to this level.

@GreenAsJade, are you able to test f21c792? I don't know how to set up rengo games.

> * This should be turned off in Zen mode

72c6c92

2024-02-06 22:28 UTC, dexonsmith commented
> @GreenAsJade, are you able to test [f21c792](https://github.com/online-go/online-go.com/commit/f21c79262c246fd0cafafd6fbd839421f79b8362)? I don't know how to set up rengo games.

Or, point me at a rengo game at beta.online-go.com where there's a title? I only see four active ones there (e.g., [this one](https://beta.online-go.com/game/13966)), and none of them sees to have "show title".

2024-02-07 02:34 UTC, GreenAsJade commented
Weird - this is what I saw this morning (sorry for rushing out without doing the screenshot then):

<img width="881" alt="Screenshot 2024-02-07 at 12 58 15 pm" src="https://github.com/online-go/online-go.com/assets/61894/14e5b3e7-e84a-423d-ae92-e47e2a6f307d">

(browser tab still open :) )

However, when I click into the same game in the Uffuzi VM now, I see this:

![Uploading Screenshot 2024-02-07 at 1.01.57 pm.png…]()


🤷‍♀️

2024-02-07 02:41 UTC, GreenAsJade commented
> > @GreenAsJade, are you able to test [f21c792](https://github.com/online-go/online-go.com/commit/f21c79262c246fd0cafafd6fbd839421f79b8362)? I don't know how to set up rengo games.
> 
> Or, point me at a rengo game at beta.online-go.com where there's a title? I only see four active ones there (e.g., [this one](https://beta.online-go.com/game/13966)), and none of them sees to have "show title".

I'll take a look as soon as I can ... it might be "cruft", but some Rengo stuff does belong in PlayCards in general because all the players are listed in there (as you've probably seen in the code).  In Rengo, the PlayerCard is the "team card".

I have a vague idea that initially games in Rengo mode had a title that said something like "Rengo mode courtesy of <whoever it was that sponsored for it, I've forgotten ☺️>"   ... maybe we stopped that showing but didn't completely remove the element 🧐

2024-02-07 02:52 UTC, dexonsmith commented
> Weird - this is what I saw this morning (sorry for rushing out without doing the screenshot then):

That's... curious. I'm not really sure how to fix it if we can't reproduce.

> I have a vague idea that initially games in Rengo mode had a title

The only content in the thing I moved comes from the `useTitle()` hook, so I think your vague idea must be it. There's also a `useShowTitle()` hook, which appears to be false for all the games I've looked at.

2024-02-07 02:56 UTC, dexonsmith commented on src/views/Game/Game.tsx
> +                                </>
Maybe, this (and the one above for portrait mode) should be a `<div>` (not a `<>`) to make the player cards and the condensed-game-info indivisible? I only have a vague idea about how layout works, but maybe the condensed-game-info is allowed to float down below the "White's move" stuff, and sometimes that's happening.

2024-02-07 03:02 UTC, dexonsmith commented on src/views/Game/Game.tsx
> +                                </>
163956d defensively does this. I don't fully understand if/why it's necessary, but...

2024-02-07 03:05 UTC, dexonsmith commented
Changed to "ready for review" since the forum seems happy enough with this. (Some debate about whether to show only "Unranked" or only "Ranked" or whichever one is relevant, but I think showing it either way will satisfy everyone.)

2024-02-09 23:45 UTC, anoek commented
Awesome, thanks for working through that all!

2024-02-09 23:45 UTC, merged