gh-2717: Fixed broken image on about page.
online-go/online-go.com pull request #2718
Opened 2024-06-17 05:26 UTC by pygeek

Fixes #

## Proposed Changes

  -
  -
  -

2024-06-17 14:33 UTC, anoek requested changes
This seems to only remove the link not fix the issue, could we fix the broken image so we have our banner still?

2024-06-17 14:47 UTC, pygeek commented
> This seems to only remove the link not fix the issue, could we fix the broken image so we have our banner still?

Sure. As a side note, the banner has been broken for 5 years.

2024-06-17 14:53 UTC, pygeek commented
> This seems to only remove the link not fix the issue, could we fix the broken image so we have our banner still?

Sure. Do you want me to use the original image as found in the archive (resolution is low), or implement a pure css solution?

As a side note, the banner has been broken for 5 years.

2024-06-17 14:55 UTC, anoek commented
> Sure. Do you want me to use the original image as found in the archive (resolution is low), or implement a pure css solution?

Awesome thanks for taking that on :) CSS sounds cleanest and most future proof, but whichever

2024-06-17 18:45 UTC, pygeek commented
> Awesome thanks for taking that on :) CSS sounds cleanest and most future proof, but whichever

I committed the original image for now, but will update this PR to use CSS.

2024-06-18 21:28 UTC, pygeek commented
Would it be possible to push this to the CDN to ensure my changes work as expected in production?

2024-06-18 22:53 UTC, anoek approved these changes

2024-06-18 22:57 UTC, anoek commented
Sure thing, https://cdn.online-go.com/5.1/img/fork_me_right_gray_6d6d6d.svg

2024-06-20 11:35 UTC, anoek commented on src/views/docs/About.tsx
> +                        src={`${cdn_release}/img/fork_me_right_gray_6d6d6.svg`}
Missing a `d` at the end of that color code, after that I think everything will work for you

2024-06-20 17:42 UTC, pygeek commented
> Sure thing, https://cdn.online-go.com/5.1/img/fork_me_right_gray_6d6d6d.svg

Thanks for uploading the image, I was able to test my changes and fix the typo. Can CI/CD be updated to deploy, and reference artifacts in the build, depending on the env context (ie: local, staging, prod)?

2024-06-21 11:53 UTC, anoek commented
> CI/CD be updated to deploy, and reference artifacts in the build, depending on the env context (ie: local, staging, prod)?

Probably not since it's a public repo, I'd like to have a human in the middle there sanity checking that.

2024-06-21 11:53 UTC, anoek commented
Thanks for the fix!

2024-06-21 11:53 UTC, merged